version: '3'
services:
  node:
    container_name: node-js-container
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo-container
    image: mongo
    ports:
      - '27017:27017'
